### ISSUE TITLE
feat: studies

### ISSUE THREAD

**Issue by devjiwonchoi** [devjiwonchoi/equine#15]
- [ ] [Export one study chapter](https://lichess.org/api#tag/Studies) - studies.export({ studyId, chapterId })
- [ ] [Export all chapters](https://lichess.org/api#tag/Studies/operation/studyAllChaptersPgn) - studies.export({ studyId })
- [ ] [Export all studies of a user](https://lichess.org/api#tag/Studies/operation/studyExportAllPgn) - studies.export({ username })
- [ ] [Study metadata](https://lichess.org/api#tag/Studies/operation/studyAllChaptersHead) - studies.metadata()
- [ ] [List studies of a user](https://lichess.org/api#tag/Studies/operation/studyListMetadata) - user.studies() vs studies.user()

**Comment by nicholasdejong** [comment]
Dear Jiwon,

I am currently using your lovely API for a personal project (I find it the best JS/TS wrapper as of right now)  and am working on a fork for this feature. 

One thing that was giving me trouble was using your stream APIs. I was unable to get any output from `lichess.events` or `lichess.board.stream`, so I have been working on a fix for stream-based APIs. It could just be that I do not understand how to use your stream APIs (which is likely), but do take a look at my current implementation. 
```js
let transformContent = {
    start() {},
    async transform(chunk, controller) {
        chunk = await chunk;
        let decoded = this.decoder.decode(chunk);
        if (decoded.trim() === '') {
            controller.enqueue({});
        } else {
            let parsed;
            try {
                parsed = JSON.parse(decoded);
            } catch (e) {
                controller.error(`Error parsing JSON: ${e}`);
                parsed = decoded;
            };
            controller.enqueue(parsed);
        }
    },
    flush() {}
};

export class JSONStream extends TransformStream {
    constructor() {
        super({ ...transformContent, decoder: new TextDecoder() });
    }
}
```

This is the code I wrote for what I call a `JSONStream`. I noticed that by default the `fetch` API's `ReadableStream`s are encoded, which means that they have to be decoded before being parsed into JSON. `JSONStream` fulfills this role by handling the decoding and JSON parsing of a `ReadableStream` from fetch. To use this stream, you have to pipe the fetch stream to a `JSONStream`:

```js
let stream = await fetch('https://lichess.org/api/tv/feed');

let json = stream.body.pipeThrough(new JSONStream());
for await (const chunk of json) {
    console.log(chunk);
};
```
Notice the `for await` iteration, a (in my opinion) very elegant way to retrieve chunks of json from the stream. I have taken a brief look at your `fetcher` and wondered whether a stream-only version (perhaps `streamer`?) could be created, which abstracts over the details and returns a `JSONStream`. 

Also, to end any `ReadableStream` yourself, you use [`ReadableStream::cancel`](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream/cancel).

Let me know what you think. I am really keen to contribute with your great work. 

Cheers,
Nicholas

**Comment by devjiwonchoi** [comment]
@nicholasdejong Hi, thank you for reaching out! Currently, this project does not support streaming at the moment. Equine is on my TODO list to work on for the stable v1, but the priority is pretty low on my list. I'm open to suggestions or PRs though, please feel free to open a PR if you'd like to implement streaming!
