### ISSUE TITLE
contribution: increasing coverage of lichess API, parsers, better error handling

### ISSUE THREAD

**Issue by LukFil** [devjiwonchoi/equine#69]
Hi,

Hope you're doing great. I wanted to ask whether you're open to contributions, and whether the following additions you'd consider useful:

* Increasing the Coverage of Lichess API: there're some endpoints that I was missing
* Zod Parsers for Data Sanity: This would help make sure our data's always in the right shape and give us clearer error messages when it's not. Plus, I'd like to implement it in a way where we could skip this step if needed.
* Better Error Messages: Building on the parsers to help us figure out whether the responses are as expected.

If all, or some of these, are interesting to you, I'd be happy to implement them. I already have some of the code for my personal project. If not, of course, no worries.
And, lastly, I'd like to ask whether there are any contribution guidelines, standards you'd like pull requests to meet (tests, coding style, whatever). 

Hope all is good with you, cheers!
Lukas

**Comment by devjiwonchoi** [comment]
Contribution is 300% welcome! I'll work on the contribution guide shortly, thank you!

**Comment by devjiwonchoi** [comment]
@LukFil Added contributing, feel free to ask on discussions if any questions or doubts. 😆

**Comment by LukFil** [comment]
Thank you, I'll get to it ASAP!
